---
# tasks file for update_repo
  - name: Install or update packages ubuntu
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: Install or update package Centos
    tags: always
    yum:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "Amazon"
